site_name: Портфолио бизнес/системного аналитика
site_description: Обезличенные примеры требований, спецификаций, API и диаграмм
site_author: Александр Попков

# Замени значения на свои
site_url: https://ayupopkov.github.io/ba-sa-portfolio/
repo_url: https://github.com/ayupopkov/ba-sa-portfolio
repo_name: ayupopkov/ba-sa-portfolio

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Главная: index.md
  - Функциональные требования: functional-requirements.md
  - Системная спецификация: system-specification.md

markdown_extensions:
  - tables
  - fenced_code
  - toc:
      permalink: true

plugins:
  - search
